const TASK_VIEW=["LIST","KANBAN"]
const COGNITO_STATUS=['ACTIVE', 'VERIFIED', 'NOT VERIFIED', 'FORCE_CHANGE_PASSWORD', 'INACTIVE', 'DELETED']
const INVITATION_STATUS=["PENDING","ACCEPT"]
const ROUTE_METHOD=["GET","POST","PUT","PATCH","DELETE"]
module.exports={
    TASK_VIEW,
    COGNITO_STATUS,
    INVITATION_STATUS,
    ROUTE_METHOD
}